'use client';

import { useCallback, useEffect, useState } from 'react';
import { useAuthStore } from '@/stores/auth-store';
import { subscribePush, unsubscribePush } from '@/lib/api/push';

// Public VAPID key exposed at build time. Generated by `npx web-push
// generate-vapid-keys` and set on Vercel as NEXT_PUBLIC_VAPID_PUBLIC_KEY.
// Matches VAPID_PUBLIC_KEY on the api (Railway).
const VAPID_PUBLIC_KEY = process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY ?? '';

export type PushPermission = 'unknown' | 'unsupported' | 'default' | 'granted' | 'denied';

function urlBase64ToUint8Array(base64String: string): Uint8Array {
  const padding = '='.repeat((4 - (base64String.length % 4)) % 4);
  const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
  const rawData = atob(base64);
  const output = new Uint8Array(rawData.length);
  for (let i = 0; i < rawData.length; ++i) output[i] = rawData.charCodeAt(i);
  return output;
}

function isSupported(): boolean {
  if (typeof window === 'undefined') return false;
  return 'serviceWorker' in navigator && 'PushManager' in window && 'Notification' in window;
}

async function getReadyServiceWorker() {
  await navigator.serviceWorker.register('/sw.js');
  return navigator.serviceWorker.ready;
}

async function toSubscribeBody(sub: PushSubscription) {
  const json = sub.toJSON() as { endpoint?: string; keys?: { p256dh?: string; auth?: string } };
  if (!json.endpoint || !json.keys?.p256dh || !json.keys?.auth) {
    console.warn('[push] subscription missing fields', json);
    return null;
  }
  return {
    endpoint: json.endpoint,
    p256dh: json.keys.p256dh,
    auth: json.keys.auth,
  };
}

/**
 * Manages the lifecycle of this device's web-push subscription:
 *  - registers the service worker
 *  - reads the current Notification.permission
 *  - exposes enable() to request permission + subscribe + POST to api
 *  - exposes disable() to unsubscribe locally + tell api to prune
 *
 * Auth-gated: subscribe only runs when an access token is in the store.
 * On logout (token cleared) the existing browser subscription stays put
 * but its server row is implicitly orphaned — the api will prune it on
 * the next push attempt (410 Gone) or the user can disable manually.
 */
export function usePush() {
  const accessToken = useAuthStore((s) => s.accessToken);
  const [permission, setPermission] = useState<PushPermission>('unknown');
  const [working, setWorking] = useState(false);

  // Detect support + initial permission.
  useEffect(() => {
    if (!isSupported()) {
      setPermission('unsupported');
      return;
    }
    setPermission(Notification.permission as PushPermission);
  }, []);

  // Register the service worker once per session.
  useEffect(() => {
    if (!isSupported()) return;
    getReadyServiceWorker().catch((err: Error) => {
      console.warn('[push] sw register failed:', err.message);
    });
  }, []);

  const syncSubscription = useCallback(async () => {
    if (!isSupported() || !accessToken || !VAPID_PUBLIC_KEY) return false;
    if (Notification.permission !== 'granted') return false;
    setWorking(true);
    try {
      const reg = await getReadyServiceWorker();
      const existing = await reg.pushManager.getSubscription();
      const sub =
        existing ??
        (await reg.pushManager.subscribe({
          userVisibleOnly: true,
          // Cast to BufferSource — modern TS lib types Uint8Array as
          // generic Uint8Array<ArrayBufferLike> which doesn't match the
          // narrower PushSubscriptionOptionsInit signature.
          applicationServerKey: urlBase64ToUint8Array(VAPID_PUBLIC_KEY) as BufferSource,
        }));
      const body = await toSubscribeBody(sub);
      if (!body) return false;
      await subscribePush(body);
      return true;
    } catch (err) {
      console.warn('[push] sync failed:', (err as Error).message);
      return false;
    } finally {
      setWorking(false);
    }
  }, [accessToken]);

  const enable = useCallback(async () => {
    if (!isSupported() || !accessToken || !VAPID_PUBLIC_KEY) return false;
    setWorking(true);
    try {
      const result = await Notification.requestPermission();
      setPermission(result as PushPermission);
      if (result !== 'granted') return false;

      return await syncSubscription();
    } catch (err) {
      console.warn('[push] enable failed:', (err as Error).message);
      return false;
    } finally {
      setWorking(false);
    }
  }, [accessToken, syncSubscription]);

  const disable = useCallback(async () => {
    if (!isSupported()) return;
    setWorking(true);
    try {
      const reg = await getReadyServiceWorker();
      const sub = await reg.pushManager.getSubscription();
      if (sub) {
        await sub.unsubscribe();
        await unsubscribePush(sub.endpoint).catch(() => undefined);
      }
    } finally {
      setWorking(false);
    }
  }, []);

  return { permission, working, enable, disable, syncSubscription, supported: isSupported() };
}
