ALTER TABLE "AiMemoryPreference" ALTER COLUMN "enabled" SET DEFAULT true;

ALTER TYPE "AiRagScope" ADD VALUE IF NOT EXISTS 'PERSONA_TEMPLATE';
ALTER TYPE "AiRagKind" ADD VALUE IF NOT EXISTS 'PERSONA_STORY';
